version: '3'
services:
  mysql:
    image: nacos/nacos-mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - ./data/env/mysql.env
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/initsql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      primihub_net:
        ipv4_address: 172.28.1.14

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - "./data:/data"
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    depends_on:
      - nacos
    networks:
      primihub_net:
        ipv4_address: 172.28.1.15

  rabbitmq1:
    image: rabbitmq:3.6.15-management
    container_name: rabbitmq1
    restart: always
    depends_on:
      - redis
    networks:
      primihub_net:
        ipv4_address: 172.28.1.16

  rabbitmq2:
    image: rabbitmq:3.6.15-management
    container_name: rabbitmq2
    restart: always
    depends_on:
      - redis
    networks:
      primihub_net:
        ipv4_address: 172.28.1.17

  rabbitmq3:
    image: rabbitmq:3.6.15-management
    container_name: rabbitmq3
    restart: always
    depends_on:
      - redis
    networks:
      primihub_net:
        ipv4_address: 172.28.1.18
  
  nacos:
    image: nacos/nacos-server:v2.0.4
    container_name: nacos-server
    restart: always
    env_file:
      - ./data/env/nacos-mysql.env
    volumes:
      - ./data/log/:/home/nacos/logs
      #- ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - node0
    networks:
      primihub_net:
        ipv4_address: 172.28.1.19

  fusion:
    image: $PRIMIHUB_FUSION
    container_name: fusion
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/fusion.jar --spring.profiles.active=dc --server.port=8080"
    # ports:
    #   - "8080:8080"
    depends_on:
      - gateway1
    networks:
      primihub_net:
        ipv4_address: 172.28.1.20
  
  application1:
    image: $PRIMIHUB_PLATFORM
    container_name: application1
    restart: always
    volumes:
      - "./data:/data"
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar --spring.profiles.active=dc1"
    depends_on:
      - rabbitmq1
    networks:
      primihub_net:
        ipv4_address: 172.28.1.21

  application2:
    image: $PRIMIHUB_PLATFORM
    container_name: application2
    restart: always
    volumes:
      - "./data:/data"
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar --spring.profiles.active=dc2"
    depends_on:
      - rabbitmq2
    networks:
      primihub_net:
        ipv4_address: 172.28.1.22

  application3:
    image: $PRIMIHUB_PLATFORM
    container_name: application3
    restart: always
    volumes:
      - "./data:/data"
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar --spring.profiles.active=dc3"
    depends_on:
      - rabbitmq3
    networks:
      primihub_net:
        ipv4_address: 172.28.1.23

  gateway1:
    image: $PRIMIHUB_PLATFORM
    container_name: gateway1
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/gateway.jar --spring.profiles.active=dc1 --server.port=8080"
    depends_on:
      - application1
    networks:
      primihub_net:
        ipv4_address: 172.28.1.24

  gateway2:
    image: $PRIMIHUB_PLATFORM
    container_name: gateway2
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/gateway.jar --spring.profiles.active=dc2 --server.port=8080"
    depends_on:
      - application2
    networks:
      primihub_net:
        ipv4_address: 172.28.1.25
  
  gateway3:
    image: $PRIMIHUB_PLATFORM
    container_name: gateway3
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/gateway.jar --spring.profiles.active=dc3 --server.port=8080"
    depends_on:
      - application3
    networks:
      primihub_net:
        ipv4_address: 172.28.1.26

  nginx1:
    image: $PRIMIHUB_WEB_MANAGE
    container_name: primihub-web1
    restart: always
    volumes:
      - "./config/default1.conf:/etc/nginx/conf.d/default.conf"
      - "./data:/data"
    ports:
      - "30811:80"
    depends_on:
      - gateway1
    networks:
      primihub_net:
        ipv4_address: 172.28.1.27

  nginx2:
    image: $PRIMIHUB_WEB_MANAGE
    container_name: primihub-web2
    restart: always
    volumes:
      - "./config/default2.conf:/etc/nginx/conf.d/default.conf"
      - "./data:/data"
    ports:
      - "30812:80"
    depends_on:
      - gateway2
    networks:
      primihub_net:
        ipv4_address: 172.28.1.28

  nginx3:
    image: $PRIMIHUB_WEB_MANAGE
    container_name: primihub-web3
    restart: always
    volumes:
      - "./config/default3.conf:/etc/nginx/conf.d/default.conf"
      - "./data:/data"
    ports:
      - "30813:80"
    depends_on:
      - gateway3
    networks:
      primihub_net:
        ipv4_address: 172.28.1.29

  node0:
    image: $PRIMIHUB_NODE
    container_name: primihub-node0
    restart: "always"
    ports:
      - "50050:50050"
      - "6666:6666"
    #   - "10120:12120"
    #   - "10121:12121"
    volumes:
      - ../../config:/app/config
      - ./data:/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./primihub-node --service_port=50050  --node_id=node0 --config=/app/config/primihub_node0.yaml"
    depends_on:
      - simple-bootstrap-node
    networks:
      primihub_net:
        ipv4_address: 172.28.1.10


  node1:
    image: $PRIMIHUB_NODE
    container_name: primihub-node1
    restart: "always"
    ports:
      - "50051:50051"
      - "6667:6667"
    #   - "11120:12120"
    #   - "11121:12121"
    volumes:
      - ../../config:/app/config
      - ./data:/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./primihub-node --service_port=50051 --node_id=node1 --config=/app/config/primihub_node1.yaml"
    depends_on:
      - simple-bootstrap-node
    networks:
      primihub_net:
        ipv4_address: 172.28.1.11


  node2:
    image: $PRIMIHUB_NODE
    container_name: primihub-node2
    restart: "always"
    ports:
      - "50052:50052"
      - "6668:6668"
    #   - "12120:12120"
    #   - "12121:12121"
    volumes:
      - ../../config:/app/config
      - ./data:/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./primihub-node --service_port=50052 --node_id=node2 --config=/app/config/primihub_node2.yaml"
    depends_on:
      - simple-bootstrap-node
    networks:
      primihub_net:
        ipv4_address: 172.28.1.12

  simple-bootstrap-node:
    image: primihub/simple-bootstrap-node:1.0
    container_name: bootstrap-node
    restart: "always"
    # ports:
    #   - "4001:4001"
    entrypoint: 
      - "/app/simple-bootstrap-node"
    depends_on:
      - mysql
    networks:
      primihub_net:
        ipv4_address: 172.28.1.13

networks:
  primihub_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1