version: 1.0

node: "node1"
location: "172.28.1.11"
grpc_port: 50051

datasets:
  # ABY3 LR test case datasets
  - description: "train_party_1"
    model: "csv"
    source: "/tmp/train_party_1.csv" 
  - description: "test_party_1"
    model: "csv"
    source: "/tmp/test_party_1.csv"
  
  # MNIST test case datasets
  - description: "test_party_1_self"
    model: "csv"
    source: "/tmp/falcon/dataset/MNIST/input_1" 
  - description: "test_party_1_next"
    model: "csv"
    source: "/tmp/falcon/dataset/MNIST/input_2" 
  
  # PIR test case dataset
  - description: "pir_server_data"
    model: "csv"
    source: "/tmp/pir_server.csv" 
  
  # PSI test case dataset
  - description: "psi_server_data"
    model: "csv"
    source: "/tmp/server_e.csv" 
  
  #  FL xgb test case datasets
  - description: "label_dataset"
    model: "csv"
    source: "/tmp/FL/wisconsin_host.data"   
  - description: "test_dataset"
    model: "csv"
    source: "/tmp/FL/wisconsin_test.data"
  - description: "breast_1"
    model: "csv"
    source: "/tmp/FL/wisconsin.data"
  - description: "homo_lr_test"
    model: "csv"
    source: "/tmp/FL/homo_lr_test.data"

localkv: 
  model: "leveldb"
  path: "/data/localdb1"

p2p:
  bootstrap_nodes:
    - "/ip4/172.28.1.13/tcp/4001/ipfs/QmP2C45o2vZfy1JXWFZDUEzrQCigMtd4r3nesvArV8dFKd"
    - "/ip4/172.28.1.13/tcp/4001/ipfs/QmdSyhb8eR9dDSR5jjnRoTDBwpBCSAjT7WueKJ9cQArYoA"
  multi_addr: "/ip4/172.28.1.11/tcp/8887"
  dht_get_value_timeout:  120

notify_server: 0.0.0.0:6667