version: 1.0

node: "node2"
location: "primihub-node2"
use_tls: false

grpc_port: 50052

#certificate:
#  root_ca: "data/cert/ca.crt"
#  key: "data/cert/node0.key"
#  cert: "data/cert/node0.crt"

meta_service:
  mode: "grpc"
  ip: "primihub-meta2"
  port: 9099
  use_tls: false

datasets:
  # ABY3 LR test case datasets
  - description: "train_party_2"
    model: "csv"
    source: "/tmp/train_party_2.csv"
  - description: "test_party_2"
    model: "csv"
    source: "/tmp/test_party_2.csv"

  # MNIST test case datasets
  - description: "test_party_2_self"
    model: "csv"
    source: "/tmp/falcon/dataset/MNIST/input_2"
  - description: "test_party_2_next"
    model: "csv"
    source: "/tmp/falcon/dataset/MNIST/input_0"

  #  FL xgb test case datasets
  - description: "guest_dataset"
    model: "csv"
    source: "/tmp/FL/wisconsin_guest.data"
  - description: "breast_2"
    model: "csv"
    source: "/tmp/FL/wisconsin.data"

  # FL homo lr test case datasets
  - description: "train_homo_lr_guest"
    model: "csv"
    source: "/tmp/FL/homo_lr/train/train_breast_cancer_guest.csv"

  # FL homo nn multiclass test case datasets
  - description: "train_homo_nn_multiclass_guest"
    model: "csv"
    source: "/tmp/FL/homo_nn/train/train_mobile_price_guest.csv"
  - description: "test_homo_nn_multiclass_guest"
    model: "csv"
    source: "/tmp/FL/homo_nn/test/test_mobile_price_guest.csv"

  # FL homo regression test case datasets
  - description: "train_homo_regression_guest"
    model: "csv"
    source: "/tmp/FL/homo_regression/train/train_boston_house_guest.csv"
  - description: "test_homo_regression_guest"
    model: "csv"
    source: "/tmp/FL/homo_regression/test/test_boston_house_guest.csv"

  # FL image test case datasets
  - description: "train_mnist_guest"
    model: "image"
    image_dir: "/tmp/FL/mnist/train/train_mnist_guest.zip"
    annotations_file: "/tmp/FL/mnist/train/train_mnist_guest_annotations.csv"
  - description: "test_mnist_guest"
    model: "image"
    image_dir: "/tmp/FL/mnist/test/test_mnist_guest.zip"
    annotations_file: "/tmp/FL/mnist/test/test_mnist_guest_annotations.csv"

  # PSI test caset datasets
  - description: "psi_client_data"
    model: "csv"
    source: "/tmp/client_e.csv"

  - description: "train_hetero_xgb_guest"
    model: "csv"
    source: "/tmp/FL/hetero_xgb/train/train_breast_cancer_guest.csv"

  - description: "test_hetero_xgb_guest"
    model: "csv"
    source: "/tmp/FL/hetero_xgb/test/test_breast_cancer_guest.csv"

