version: 1.0

node: "node2"
location: "primihub-node2"
use_tls: false

grpc_port: 50052

#certificate:
#  root_ca: "data/cert/ca.crt"
#  key: "data/cert/node0.key"
#  cert: "data/cert/node0.crt"

meta_service:
  mode: "grpc"
  ip: "primihub-meta2"
  port: 9099
  use_tls: false

datasets:
  # ABY3 LR test case datasets
  - description: "train_party_2"
    model: "csv"
    source: "data/train_party_2.csv"
  - description: "test_party_2"
    model: "csv"
    source: "data/test_party_2.csv"

  # MNIST test case datasets
  - description: "test_party_2_self"
    model: "csv"
    source: "data/falcon/dataset/MNIST/input_2"
  - description: "test_party_2_next"
    model: "csv"
    source: "data/falcon/dataset/MNIST/input_0"

  # FL binclass
  - description: "binclass_hfl_train_client2"
    model: "csv"
    source: "data/FL/binclass/hfl/train/client2.csv"
  - description: "binclass_hfl_test_client2"
    model: "csv"
    source: "data/FL/binclass/hfl/test/client2.csv"

  # FL multiclass
  - description: "multiclass_hfl_train_client2"
    model: "csv"
    source: "data/FL/multiclass/hfl/train/client2.csv"
  - description: "multiclass_hfl_test_client1"
    model: "csv"
    source: "data/FL/multiclass/hfl/test/client2.csv"

  # FL regression
  - description: "regression_hfl_train_client2"
    model: "csv"
    source: "data/FL/regression/hfl/train/client2.csv"
  - description: "regression_hfl_test_client2"
    model: "csv"
    source: "data/FL/regression/hfl/test/client2.csv"

  # FL mnist image classification
  - description: "mnist_train_client2"
    model: "image"
    image_dir: "data/FL/mnist/train/client2.zip"
    annotations_file: "data/FL/mnist/train/client2_annotations.csv"
  - description: "mnist_test_client2"
    model: "image"
    image_dir: "data/FL/mnist/test/client2.zip"
    annotations_file: "data/FL/mnist/test/client2_annotations.csv"

  ## PSI test caset datasets
  #- description: "psi_client_data"
  #  model: "csv"
  #  source: "data/client_e.csv"

  # PSI test case datasets for sqlite database
  #- description: "psi_client_data_db"
  #  model: "sqlite"
  #  table_name: "psi_client_data"
  #  source: "data/client_e.db3"

  - description: "train_hetero_xgb_guest"
    model: "csv"
    source: "data/FL/hetero_xgb/train/train_breast_cancer_guest.csv"

  - description: "test_hetero_xgb_guest"
    model: "csv"
    source: "data/FL/hetero_xgb/test/test_breast_cancer_guest.csv"

  - description: "iv_filter_guest"
    model: "csv"
    source: "data/FL/hetero_iv/iv_guest.csv"
  
  # FL preprocess
  - description: "preprocess_vfl_train_guest"
    model: "csv"
    source: "data/FL/preprocess/vfl/train/guest.csv"
  - description: "preprocess_vfl_test_guest"
    model: "csv"
    source: "data/FL/preprocess/vfl/test/guest.csv"
  - description: "preprocess_hfl_train_client2"
    model: "csv"
    source: "data/FL/preprocess/hfl/train/client2.csv"
  - description: "preprocess_hfl_test_client2"
    model: "csv"
    source: "data/FL/preprocess/hfl/test/client2.csv"

  # MPC statistics & arithmetic
  - description: "mpc_statistics_2"
    model: "csv"
    source: "data/mpc_test.csv"
  - description: "mpc_arithmetic_2"
    model: "csv"
    source: "data/mpc_arithmetic_2.csv"
