version: 1.0

node: "node1"
location: "primihub-node1"
use_tls: false

grpc_port: 50051

#certificate:
#  root_ca: "data/cert/ca.crt"
#  key: "data/cert/node0.key"
#  cert: "data/cert/node0.crt"

meta_service:
  mode: "grpc"
  ip: "primihub-meta1"
  port: 9099
  use_tls: false

datasets:
  # ABY3 LR test case datasets
  - description: "train_party_1"
    model: "csv"
    source: "/tmp/train_party_1.csv"
  - description: "test_party_1"
    model: "csv"
    source: "/tmp/test_party_1.csv"

  # MNIST test case datasets
  - description: "test_party_1_self"
    model: "csv"
    source: "/tmp/falcon/dataset/MNIST/input_1"
  - description: "test_party_1_next"
    model: "csv"
    source: "/tmp/falcon/dataset/MNIST/input_2"

  # PIR test case dataset
  - description: "pir_server_data"
    model: "csv"
    source: "/tmp/pir_server.csv"

  # keyword PIR test case dataset
  - description: "keyword_pir_server_data"
    model: "csv"
    source: "/tmp/keyword_pir_server.csv"

  # PSI test case dataset
  - description: "psi_server_data"
    model: "csv"
    source: "/tmp/server_e.csv"

  #  FL xgb test case datasets
  - description: "label_dataset"
    model: "csv"
    source: "/tmp/FL/wisconsin_host.data"
  - description: "test_dataset"
    model: "csv"
    source: "/tmp/FL/wisconsin_test.data"
  - description: "breast_1"
    model: "csv"
    source: "/tmp/FL/wisconsin.data"
  - description: "homo_lr_test"
    model: "csv"
    source: "/tmp/FL/homo_lr_test.data"

  - description: "train_hetero_xgb_host"
    model: "csv"
    source: "/tmp/FL/hetero_xgb/train/train_breast_cancer_host.csv"

  - description: "test_hetero_xgb_host"
    model: "csv"
    source: "/tmp/FL/hetero_xgb/test/test_breast_cancer_host.csv"

  # FL homo lr test case datasets
  - description: "train_homo_lr_host"
    model: "csv"
    source: "/tmp/FL/homo_lr/train/train_breast_cancer_host.csv"
  - description: "test_homo_lr"
    model: "csv"
    source: "/tmp/FL/homo_lr/test_breast_cancer.csv"

  # FL homo nn multiclass test case datasets
  - description: "train_homo_nn_multiclass_host"
    model: "csv"
    source: "/tmp/FL/homo_nn/train/train_mobile_price_host.csv"
  - description: "test_homo_nn_multiclass_host"
    model: "csv"
    source: "/tmp/FL/homo_nn/test/test_mobile_price_host.csv"

  # FL homo regression test case datasets
  - description: "train_homo_regression_host"
    model: "csv"
    source: "/tmp/FL/homo_regression/train/train_boston_house_host.csv"
  - description: "test_homo_regression_host"
    model: "csv"
    source: "/tmp/FL/homo_regression/test/test_boston_house_host.csv"

  # FL image test case datasets
  - description: "train_mnist_host"
    model: "image"
    image_dir: "/tmp/FL/mnist/train/train_mnist_host.zip"
    annotations_file: "/tmp/FL/mnist/train/train_mnist_host_annotations.csv"
  - description: "test_mnist_host"
    model: "image"
    image_dir: "/tmp/FL/mnist/test/test_mnist_host.zip"
    annotations_file: "/tmp/FL/mnist/test/test_mnist_host_annotations.csv"

